name: Test

on: [push]

jobs:
  test:
    runs-on: macos-latest # Use macos for iOS simulator support

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # Updated to v2
        with:
          channel: 'stable'

      - name: Start iOS Simulator # Add this step for iOS
        uses: futureware-tech/simulator-action@v1  # Install & Start simulator
        with:
          model: 'iPhone 15' # Choose your desired simulator model

      - name: Build app
        run: flutter build ios # Build iOS app

      - name: Install Dependencies (Maestro, IDB Companion)
        run: |
          brew tap facebook/fb
          brew install maestro
          brew install facebook/fb/idb-companion

      - name: Run Maestro Tests
        run: maestro test filename.yml  # Use the full path to filename.yml
        env:
          FLUTTER_VERSION: stable

      # Optional: If testing on Android
      #- name: Start Android Emulator (if needed)
      #  uses: reactivecircus/android-emulator-runner@v2 
      #  with: 
      #    api-level: 29
      #    arch: x86_64

      #- name: Run tests on Android (if needed)
      #  run: maestro test filename.yml -d emulator-5554 # Replace with correct emulator name
